-- Número 1
SELECT LAST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE SUBSTR(LAST_NAME, 1, 1) = 'R';


-- Número 2
SELECT CONCAT(CONCAT(FIRST_NAME, ' '), LAST_NAME) AS FULL_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 60;


-- Número 3
SELECT UPPER(DEPARTMENT_NAME) AS DEPARTMENT_NAME
FROM DEPARTMENTS
WHERE DEPARTMENT_ID = 60;


-- Número 4
SELECT CONCAT(CONCAT(FIRST_NAME, ' '), LAST_NAME) AS FULL_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE >= '01/01/1999' AND HIRE_DATE <= '31/12/1999';


-- Número 5
SELECT
    FIRST_NAME,
    SALARY*12 AS ANUAL_SALARY
FROM EMPLOYEES
WHERE SALARY >= 4000 AND SALARY <= 7000;


-- Número 6
SELECT 
    CONCAT(CONCAT(E.FIRST_NAME, ' '), E.LAST_NAME) AS FULL_NAME
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE D.DEPARTMENT_NAME = 'Shipping';


-- Número 7
SELECT 
    E.FIRST_NAME
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE 
    D.DEPARTMENT_NAME = 'Shipping' AND
    E.SALARY >= 5000 AND E.SALARY <= 8000 AND
    E.HIRE_DATE >= '01/01/1997' AND E.HIRE_DATE <= '31/12/1999';
    
    
-- Número 8
SELECT 
    CONCAT(CONCAT(FIRST_NAME, ' '), LAST_NAME) AS FULL_NAME
FROM EMPLOYEES
WHERE MANAGER_ID = (SELECT EMPLOYEE_ID 
    FROM EMPLOYEES 
    WHERE (CONCAT(CONCAT(FIRST_NAME, ' '), LAST_NAME) = 'Steven King'));
