-- Questão 1 - Utilizando MINUS
SELECT DEPARTMENT_NAME 
FROM DEPARTMENTS
MINUS
SELECT DEPARTMENT_NAME 
FROM DEPARTMENTS D
JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID;

-- Questão 1 - Utilizando consulta aninhada com NOT IN
SELECT DEPARTMENT_NAME 
FROM DEPARTMENTS 
WHERE DEPARTMENT_NAME NOT IN (SELECT DEPARTMENT_NAME
                FROM DEPARTMENTS D
                JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID);

-- Questão 2
SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- Questão 3

SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E LEFT OUTER 
JOIN DEPARTMENTS D on D.DEPARTMENT_ID=E.DEPARTMENT_ID;
       
-- Questão 4
SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_NAME
FROM DEPARTMENTS D RIGHT OUTER 
JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID;

-- Questão 5
SELECT E.FIRST_NAME, E.LAST_NAME, J.START_DATE, J.END_DATE, J.JOB_ID
FROM EMPLOYEES E LEFT JOIN JOB_HISTORY J ON E.EMPLOYEE_ID = J.EMPLOYEE_ID;

-- Questão 6
SELECT E.FIRST_NAME, E.LAST_NAME, JH.START_DATE, JH.END_DATE, JH.JOB_ID, J.JOB_TITLE
FROM (EMPLOYEES E 
LEFT OUTER JOIN JOB_HISTORY JH
ON E.EMPLOYEE_ID=JH.EMPLOYEE_ID) 
LEFT JOIN JOBS J
ON JH.JOB_ID = J.JOB_ID;
       
-- Questão 7
SELECT J.JOB_TITLE
FROM JOBS J  
WHERE J.JOB_ID IN (SELECT DISTINCT E.JOB_ID
                   FROM EMPLOYEES E  
                   WHERE E.DEPARTMENT_ID IN (SELECT D.DEPARTMENT_ID
                                             FROM DEPARTMENTS D        
                                             WHERE D.LOCATION_ID IN (SELECT L.LOCATION_ID
                                                                     FROM LOCATIONS L 
                                                                     WHERE L.CITY='Seattle')));


-- Questão 8
SELECT DISTINCT J.JOB_TITLE 
FROM LOCATIONS L 
JOIN DEPARTMENTS D ON L.LOCATION_ID = D.LOCATION_ID
JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
JOIN JOBS J ON E.JOB_ID = J.JOB_ID
WHERE L.CITY='Seattle';