CREATE TABLE FUNCIONARIO (
    PRIMEIRO_NOME VARCHAR(50),
    NOME_MEIO VARCHAR(50),
    ULTIMO_NOME VARCHAR(50),
    CPF VARCHAR(11) PRIMARY KEY,
    DATA_NASCIMENTO DATE,
    ENDERECO VARCHAR(50),
    SEXO CHAR,
    SALARIO INT,
    FOREIGN KEY CPF_SUPERVISOR REFERENCES FUNCIONARIO(CPF),
    FOREIGN KEY NUMERO_DEPARTAMENTO REFERENCES DEPARTAMENTO(NUMERO_DEPARTAMENTO) 
);

CREATE TABLE DEPARTAMENTO (
    NOME_DEPARTAMENTO VARCHAR(50) PRIMARY KEY,
    NUMERO_DEPARTAMENTO INT,
    FOREIGN KEY CPF_GERENTE REFERENCES FUNCIONARIO(CPF),
    DATA_INICIO_GERENTE DATE
);

CREATE TABLE LOCALIZACOES_DEPARTAMENTO (
    FOREIGN KEY NUMERO_DEPARTAMENTO REFERENCES DEPARTAMENTO(NUMERO_DEPARTAMENTO),
    LOCAL_ VARCHAR(50) --Verificar com o Evandrino se pode, pois LOCAL ele identifica como variável restrita
);

CREATE TABLE PROJETO (
    NOME_PROJETO VARCHAR(50),
    NUMERO_PROJETO INT,
    LOCAL_PROJETO VARCHAR(50),
    FOREIGN KEY NUMERO_DEPARTAMENTO REFERENCES DEPARTAMENTO(NUMERO_DEPARTAMENTO)
);

CREATE TABLE TRABALHA_EM (
    FOREIGN KEY CPF_FUNCIONARIO REFERENCES FUNCIONARIO(CPF),
    FOREIGN KEY NUMERO_PROJETO REFERENCES PROJETO(NUMERO_PROJETO),
    HORAS INT
);

CREATE TABLE DEPENDENTE (
    FOREIGN KEY CPF_FUNCIONARIO REFERENCES FUNCIONARIO(CPF),
    NOME_DEPENDENTE VARCHAR(50),
    SEXO CHAR,
    DATA_NASCIMENTO DATE,
    PARENTESCO VARCHAR(50)
);