
-- Questão 1 - Utilizando MINUS
SELECT DEPARTMENT_NAME 
FROM DEPARTMENTS
MINUS
SELECT DEPARTMENT_NAME 
FROM DEPARTMENTS D
JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID;

-- Questão 1 - Utilizando consulta aninhada com NOT IN
SELECT DEPARTMENT_NAME 
FROM DEPARTMENTS 
WHERE DEPARTMENT_NAME NOT IN (SELECT DEPARTMENT_NAME
                FROM DEPARTMENTS D
                JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID);

-- Questão 2
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_NAME
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- Questão 3
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_NAME; --incompleto


SELECT * FROM EMPLOYEES;