CREATE TABLE TIME (
    ID INT,
    NOME VARCHAR(50)
);

CREATE TABLE JOGO (
    DATA DATE,
    PLACAR_CASA INT,
    PLACAR_VISITANTE INT
);

CREATE TABLE JOGADOR (
    CPF VARCHAR(11),
    NOME VARCHAR(50)
);

INSERT INTO TIME(ID, NOME)
VALUES (1, 'Flamengo');
INSERT INTO TIME(ID, NOME)
VALUES (2, 'Bahia');
INSERT INTO TIME(ID, NOME)
VALUES (3, 'Grêmio');

INSERT INTO JOGO(DATA, PLACAR_CASA, PLACAR_VISITANTE) 
VALUES ('04-04-2024', 3, 1);
INSERT INTO JOGO(DATA, PLACAR_CASA, PLACAR_VISITANTE) 
VALUES ('01-04-2024', 1, 0);
INSERT INTO JOGO(DATA, PLACAR_CASA, PLACAR_VISITANTE) 
VALUES ('27-03-2024', 2, 2);

INSERT INTO JOGADOR(CPF, NOME)
VALUES('12345678911', 'Matheus');
INSERT INTO JOGADOR(CPF, NOME)
VALUES('12345678955', 'João');
INSERT INTO JOGADOR(CPF, NOME)
VALUES('12345678988', 'Pedro');

ALTER TABLE TIME 
ADD CONSTRAINT PK_TIME PRIMARY KEY (ID);
ALTER TABLE JOGADOR
ADD CONSTRAINT PK_JOGADOR PRIMARY KEY (CPF);

ALTER TABLE JOGO 
ADD ID_CASA INT;
ALTER TABLE JOGO
ADD ID_VISITANTE INT;
ALTER TABLE JOGADOR 
ADD ID_TIME INT;

ALTER TABLE JOGO
ADD CONSTRAINT FK_JOGOIDCASA_TIMEID FOREIGN KEY (ID_CASA) REFERENCES TIME(ID) ON DELETE CASCADE;
ALTER TABLE JOGO 
ADD CONSTRAINT FK_JOGOIDVISITANTE_TIMEID FOREIGN KEY (ID_VISITANTE) REFERENCES TIME(ID) ON DELETE CASCADE;
ALTER TABLE JOGADOR
ADD CONSTRAINT FK_JOGADORIDTIME_TIMEID FOREIGN KEY (ID_TIME) REFERENCES TIME(ID);

UPDATE JOGO
SET ID_CASA = 1
WHERE PLACAR_CASA = 3;
UPDATE JOGO
SET ID_VISITANTE = 2
WHERE PLACAR_VISITANTE = 1;

UPDATE JOGO
SET ID_CASA = 1
WHERE PLACAR_CASA = 1;
UPDATE JOGO
SET ID_VISITANTE = 3
WHERE PLACAR_VISITANTE = 0;

UPDATE JOGO
SET ID_CASA = 2
WHERE PLACAR_CASA = 2;
UPDATE JOGO
SET ID_VISITANTE = 3
WHERE PLACAR_VISITANTE = 2;

UPDATE JOGADOR
SET ID_TIME = 1
WHERE NOME = 'Matheus';
UPDATE JOGADOR
SET ID_TIME = 2
WHERE NOME = 'João';
UPDATE JOGADOR
SET ID_TIME = 3
WHERE NOME = 'Pedro';

ALTER TABLE JOGO
ADD CONSTRAINT PK_IDCASA_IDVISITANTE_DATA_JOGO PRIMARY KEY(ID_CASA, ID_VISITANTE, DATA);

ALTER TABLE JOGADOR 
MODIFY ID_TIME INT NOT NULL;

ALTER TABLE JOGADOR
MODIFY NOME VARCHAR(50) UNIQUE;