INSERT INTO DEPARTAMENTO (NOME_DEPARTAMENTO, NUMERO_DEPARTAMENTO, CPF_GERENTE, DATA_INICIO_GERENTE)
VALUES ('Matriz', 1, NULL, TO_DATE('19-06-1981', 'DD-MM-YYYY'));

UPDATE DEPARTAMENTO
SET CPF_GERENTE = '88866555576'
WHERE NUMERO_DEPARTAMENTO = 1;


INSERT INTO FUNCIONARIO (PRIMEIRO_NOME, NOME_MEIO, ULTIMO_NOME, CPF, DATA_NASCIMENTO, ENDERECO, SEXO, SALARIO, CPF_SUPERVISOR, NUMERO_DEPARTAMENTO)
VALUES ('Jorge', 'E', 'Brito', '88866555576',TO_DATE('10-11-1937', 'DD-MM-YYYY'), 'Rua do Horto, 35, São Paulo, SP', 'M', 55000, NULL, 1);



INSERT INTO DEPARTAMENTO (NOME_DEPARTAMENTO, NUMERO_DEPARTAMENTO, CPF_GERENTE, DATA_INICIO_GERENTE)
VALUES ('Pesquisa', 5, '33344555587', '22-05-1968');






-- Inserção na tabela FUNCIONARIO
INSERT INTO FUNCIONARIO (PRIMEIRO_NOME, NOME_MEIO, ULTIMO_NOME, CPF, DATA_NASCIMENTO, ENDERECO, SEXO, SALARIO, CPF_SUPERVISOR, NUMERO_DEPARTAMENTO)
VALUES ('', '', '', '', TO_DATE('XX-XX-XXXX', 'YYYY-MM-DD'), '', '', , '', );

-- Inserção na tabela DEPARTAMENTO
INSERT INTO DEPARTAMENTO (NOME_DEPARTAMENTO, NUMERO_DEPARTAMENTO, CPF_GERENTE, DATA_INICIO_GERENTE)
VALUES ('', , '', 'YYYY-MM-DD');

-- Inserção na tabela LOCALIZACOES_DEPARTAMENTO
INSERT INTO LOCALIZACOES_DEPARTAMENTO (NUMERO_DEPARTAMENTO, LOCAL_)
VALUES (, '');

-- Inserção na tabela PROJETO
INSERT INTO PROJETO (NOME_PROJETO, NUMERO_PROJETO, LOCAL_PROJETO, NUMERO_DEPARTAMENTO)
VALUES ('', , '', );

-- Inserção na tabela TRABALHA_EM
INSERT INTO TRABALHA_EM (CPF_FUNCIONARIO, NUMERO_PROJETO, HORAS)
VALUES ('', , );

-- Inserção na tabela DEPENDENTE
INSERT INTO DEPENDENTE (CPF_FUNCIONARIO, NOME_DEPENDENTE, SEXO, DATA_NASCIMENTO, PARENTESCO)
VALUES ('', '', '', 'YYYY-MM-DD', '');
