-- Nome: Matheus Monteiro Huebra Perdigão
--       Letícia de Oliveira Soares


-- Questão 1

CREATE TABLE INSTITUICAO (
    NOME VARCHAR(50) PRIMARY KEY,
    ENDERECO VARCHAR(100)
);

CREATE TABLE DEPARTAMENTO (
    COD_DEP INT PRIMARY KEY,
    NOME VARCHAR(50),
    NOME_INSTITUICAO VARCHAR(50),
    QUANT_PESQUISADORES INT
);

ALTER TABLE DEPARTAMENTO ADD CONSTRAINT FK_NOMEINSTITUICAO_NOME FOREIGN KEY (NOME_INSTITUICAO) REFERENCES INSTITUICAO(NOME) ON DELETE CASCADE;

CREATE TABLE PESQUISADOR (
    COD_DEP INT,
    NOME VARCHAR(50),
    DATA_NASCIMENTO DATE
);

DROP TABLE PESQUISADOR;

ALTER TABLE PESQUISADOR ADD CONSTRAINT PK_NOME_CODDEP PRIMARY KEY (NOME, COD_DEP);
ALTER TABLE PESQUISADOR ADD CONSTRAINT FK_CODDEP_CODDEPDEPARTAMENTO FOREIGN KEY (COD_DEP) REFERENCES DEPARTAMENTO(COD_DEP) ON DELETE CASCADE;

INSERT INTO INSTITUICAO(NOME, ENDERECO)
VALUES('CEFET-MG', 'Av. Amazonas 7675');

INSERT INTO INSTITUICAO(NOME, ENDERECO)
VALUES('PUC-MG', 'Rua Coração Eucarístico 0');

INSERT INTO DEPARTAMENTO(COD_DEP, NOME, NOME_INSTITUICAO, QUANT_PESQUISADORES)
VALUES(1, 'DECOM', 'CEFET-MG', 3);

INSERT INTO DEPARTAMENTO(COD_DEP, NOME, NOME_INSTITUICAO, QUANT_PESQUISADORES)
VALUES(2, 'DF', 'PUC-MG', 2);

INSERT INTO PESQUISADOR(COD_DEP, NOME, DATA_NASCIMENTO)
VALUES(1, 'Evandrino', '12-11-1990');

INSERT INTO PESQUISADOR(COD_DEP, NOME, DATA_NASCIMENTO)
VALUES(2, 'Fausto', '13-05-1978');

SELECT * FROM INSTITUICAO;
SELECT * FROM DEPARTAMENTO;
SELECT * FROM PESQUISADOR;

/*
'CEFET-MG', 'Av. Amazonas 7675'
'PUC-MG', 'Rua Coração Eucarístico 0'

2, 'DF', 'PUC-MG', 2
1, 'DECOM', 'CEFET-MG', 3

1, 'Evandrino', '12/11/90'
2, 'Fausto', '13/05/78'
*/

-- Questão 2

-- LETRA A)
ALTER TABLE DEPARTAMENTO
DROP CONSTRAINT FK_NOMEINSTITUICAO_NOME;

ALTER TABLE INSTITUICAO
DROP PRIMARY KEY;

-- Letra B)

ALTER TABLE INSTITUICAO
ADD COD_INSTITUICAO INT;

UPDATE INSTITUICAO
SET COD_INSTITUICAO = 1
WHERE NOME = 'CEFET-MG';

COMMIT;

UPDATE INSTITUICAO
SET COD_INSTITUICAO = 2
WHERE NOME = 'PUC-MG';

COMMIT;

ALTER TABLE INSTITUICAO
ADD CONSTRAINT PK_COD_INSTITUICAO PRIMARY KEY(COD_INSTITUICAO);

-- Letra C)

ALTER TABLE DEPARTAMENTO
ADD COD_INSTITUICAO INT;

ALTER TABLE DEPARTAMENTO
DROP COLUMN NOME_INSTITUICAO;

UPDATE DEPARTAMENTO
SET COD_INSTITUICAO = 1
WHERE NOME = 'DECOM';

COMMIT;

UPDATE DEPARTAMENTO
SET COD_INSTITUICAO = 2
WHERE NOME = 'DF';

COMMIT;

ALTER TABLE DEPARTAMENTO
ADD CONSTRAINT FK_CODINSTITUICAO_CODINSTITUICAO FOREIGN KEY (COD_INSTITUICAO) REFERENCES INSTITUICAO(COD_INSTITUICAO) ON DELETE CASCADE;

SELECT * FROM INSTITUICAO;
SELECT * FROM DEPARTAMENTO;
SELECT * FROM PESQUISADOR;

/*
'CEFET-MG', 'Av. Amazonas 7675', 1
'PUC-MG', 'Rua Coração Eucarístico 0', 2

2, 'DF', 2, 2
1, 'DECOM', 3, 1

1, 'Evandrino', '12/11/90'
2, 'Fausto', '13/05/78'
*/

-- Questão 3

CREATE OR REPLACE TRIGGER ATUALIZA_QUANT_PESQUISADORES
AFTER INSERT OR UPDATE OF COD_DEP ON PESQUISADOR
FOR EACH ROW
BEGIN
    --IF (:NEW.COD_DEP != :OLD.COD_DEP) THEN
        UPDATE DEPARTAMENTO D
        SET QUANT_PESQUISADORES = QUANT_PESQUISADORES + 1
        WHERE D.COD_DEP = :NEW.COD_DEP;

        UPDATE DEPARTAMENTO D
        SET QUANT_PESQUISADORES = QUANT_PESQUISADORES - 1
        WHERE D.COD_DEP = :OLD.COD_DEP;
    --END IF;
END;
/


INSERT INTO PESQUISADOR(COD_DEP, NOME, DATA_NASCIMENTO)
VALUES(1, 'Matheus', '09-06-2003');

INSERT INTO PESQUISADOR(COD_DEP, NOME, DATA_NASCIMENTO)
VALUES(2, 'Letícia', '31-07-2003');

/*
Antes da adição de um novo pesquisador:
(A terceira coluna é a QUANT_PESQUISADORES)

2, 'DF', 1, 2
1, 'DECOM', 1, 1

Após a adição de um novo pesquisador em cada departamento:

2, 'DF', 2, 2
1, 'DECOM', 2, 1
*/

UPDATE PESQUISADOR
SET COD_DEP = 1
WHERE NOME = 'Letícia';

/*
Após trocar alguém de departamento:

2, 'DF', 1, 2
1, 'DECOM', 3, 1
*/

SELECT * FROM PESQUISADOR;
SELECT * FROM DEPARTAMENTO;