CREATE TABLE COUNTRIES AS SELECT * FROM SH.COUNTRIES;

SELECT * FROM COUNTRIES
WHERE COUNTRY_ID = 52771;

EXPLAIN PLAN FOR
SELECT * FROM COUNTRIES
WHERE COUNTRY_ID = 52771;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);