-- Nome: Matheus Monteiro Huebra Perdigão
--       Letícia de Oliveira Soares

-- Questão 1
-- b)
CREATE TABLE PESSOA (
    CPF VARCHAR(11) PRIMARY KEY, 
    CPF_CONJUGE_ATUAL VARCHAR(11),
    DTNASCIMENTO DATE,
    CPF_PAI VARCHAR(11),
    CPF_MAE VARCHAR(11),
    IDADE INT
);

ALTER TABLE PESSOA ADD CONSTRAINT FK_CONJUGE_CPF FOREIGN KEY (CPF_CONJUGE_ATUAL) REFERENCES PESSOA(CPF);
ALTER TABLE PESSOA ADD CONSTRAINT FK_PAI_CPF FOREIGN KEY (CPF_PAI) REFERENCES PESSOA(CPF);
ALTER TABLE PESSOA ADD CONSTRAINT FK_MAE_CPF FOREIGN KEY (CPF_MAE) REFERENCES PESSOA(CPF);

CREATE TABLE CASAMENTO_ANTERIOR (
    CPF_CONJUGE1 VARCHAR(11),
    CPF_CONJUGE2 VARCHAR(11),
    PRIMARY KEY (CPF_CONJUGE1, CPF_CONJUGE2)
);


ALTER TABLE CASAMENTO_ANTERIOR ADD CONSTRAINT FK_CONJUGE1_CPF FOREIGN KEY (CPF_CONJUGE1) REFERENCES PESSOA(CPF);
ALTER TABLE CASAMENTO_ANTERIOR ADD CONSTRAINT FK_CONJUGE2_CPF FOREIGN KEY (CPF_CONJUGE2) REFERENCES PESSOA(CPF);

-- Questão 1
-- c)

ALTER TABLE PESSOA ADD CONSTRAINT MONOGAMIA UNIQUE (CPF_CONJUGE_ATUAL);

-- Questão 1
-- d)

CREATE OR REPLACE TRIGGER CALCULA_IDADE
BEFORE INSERT OR UPDATE OF DTNASCIMENTO ON PESSOA
FOR EACH ROW
BEGIN
    :NEW.IDADE := FLOOR((SYSDATE - :NEW.DTNASCIMENTO) / 365);
END;
/

-- Teste da constraint MONOGAMIA
/*
INSERT INTO PESSOA (CPF, DTNASCIMENTO) VALUES ('12345678901', '09/06/2000');
INSERT INTO PESSOA (CPF, DTNASCIMENTO) VALUES ('98765432100', '15/08/1998');

UPDATE PESSOA SET CPF_CONJUGE_ATUAL = '98765432100' WHERE CPF = '12345678901';

INSERT INTO PESSOA (CPF, DTNASCIMENTO, CPF_CONJUGE_ATUAL) VALUES ('11223344556', '23/03/1997', '98765432100');
*/

-- Teste do trigger CALCULA_IDADE

/*
INSERT INTO PESSOA (CPF, DTNASCIMENTO) VALUES ('24681357901', '09/06/2003'); -- 21 anos
*/